from __future__ import annotations

import argparse
import json
import os
import subprocess
import time
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
SECURITY_EVIDENCE = ROOT / "artifacts" / "operations" / "v1.9.0-phase3"
CRITICAL_EVIDENCE = ROOT / "artifacts" / "operations" / "v1.9.0-phase4a"
RUNTIME_EVIDENCE = ROOT / "artifacts" / "runtime" / "v1.9.0-phase2"
OUTPUT_DIR = ROOT / "artifacts" / "release" / "v1.9.0-public-preview"

REQUIRED_CHECKS = {
    "repository-hygiene",
    "java-test",
    "python-test",
    "admin-build",
    "customer-build",
    "gitleaks",
    "public-runtime-phase2",
    "public-container-security",
    "public-operations-phase3",
    "public-critical-zero-phase4a",
}


def _source_commit() -> str:
    return os.getenv("GITHUB_SHA") or subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=str(ROOT), text=True).strip()


def _load(path: Path) -> dict[str, Any]:
    if not path.exists() or path.stat().st_size == 0:
        raise RuntimeError(f"missing or empty evidence file: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def _validate_security() -> dict[str, Any]:
    security = _load(SECURITY_EVIDENCE / "container-security-summary.json")
    _require(security.get("scanCompleted") is True, "security scanCompleted must be true")
    _require(security.get("criticalFindingCount") == 0, "criticalFindingCount must be zero")
    _require(security.get("exceptionedCriticalCount") == 0, "exceptionedCriticalCount must be zero")
    _require(security.get("unexceptionedCriticalCount") == 0, "unexceptionedCriticalCount must be zero")
    _require(security.get("unexceptionedHighCount") == 0, "unexceptionedHighCount must be zero")
    _require(security.get("invalidExceptionCount") == 0, "invalidExceptionCount must be zero")
    _require(security.get("expiredExceptionCount") == 0, "expiredExceptionCount must be zero")
    _require(security.get("orphanExceptionCount") == 0, "orphanExceptionCount must be zero")
    _require(security.get("duplicateExceptionCount") == 0, "duplicateExceptionCount must be zero")
    _require(security.get("exceptionedHighCount", 0) == security.get("highFindingCount", 0), "all HIGH findings must be tracked as exceptions")

    critical_zero = _load(CRITICAL_EVIDENCE / "critical-zero-summary.json")
    _require(critical_zero.get("status") == "PASS", "critical zero status must be PASS")
    _require(critical_zero.get("criticalFindingCount") == 0, "critical zero finding count must be zero")
    _require(critical_zero.get("criticalExceptionCount") == 0, "critical zero exception count must be zero")
    _require(critical_zero.get("newHighFindingCount") == 0, "newHighFindingCount must be zero")
    return {"container": security, "criticalZero": critical_zero}


def _validate_runtime() -> dict[str, Any]:
    health = _load(RUNTIME_EVIDENCE / "health-summary.json")
    business = _load(RUNTIME_EVIDENCE / "business-smoke-summary.json")
    failure = _load(RUNTIME_EVIDENCE / "failure-smoke-summary.json")
    runtime_gate = _load(RUNTIME_EVIDENCE / "gate-result.json")
    _require(runtime_gate.get("publicRuntimeVerified") is True, "public runtime must be verified")
    _require(runtime_gate.get("productionReady") is False, "runtime gate must not claim production readiness")
    _require(runtime_gate.get("gates", {}).get("businessSmokeE2E") == "PASS", "business E2E must be PASS")
    _require(runtime_gate.get("gates", {}).get("aiUnavailableBehavior") == "PASS", "AI unavailable behavior must be PASS")
    return {"health": health, "business": business, "failure": failure, "gate": runtime_gate}


def _validate_operations() -> dict[str, Any]:
    phase3 = _load(SECURITY_EVIDENCE / "phase3-gate-result.json")
    _require(phase3.get("status") in {"PARTIAL", "PASS"}, "phase3 status must be PARTIAL or PASS")
    checks = phase3.get("checks") or {}
    for key in ["observability", "mysqlLogicalProbeRestore", "sbom", "backendRestartRecovery"]:
        _require(checks.get(key) == "PASS", f"phase3 {key} must be PASS")
    _require(checks.get("containerRiskBaseline") in {"BLOCKED", "PASS"}, "container risk baseline must be audited")
    return phase3


def _validate_sbom() -> dict[str, Any]:
    manifest = _load(SECURITY_EVIDENCE / "sbom" / "manifest.json")
    _require(manifest.get("status") == "PASS", "SBOM manifest status must be PASS")
    _require(manifest.get("tool") == "trivy", "SBOM must be generated by Trivy")
    _require(set((manifest.get("images") or {}).keys()) == {"backend", "ai-service", "admin", "customer"}, "SBOM must include all public images")
    for image in (manifest.get("images") or {}).values():
        sbom_path = ROOT / image.get("sbomPath", "")
        _require(sbom_path.exists() and sbom_path.stat().st_size > 0, f"SBOM file missing: {sbom_path}")
        json.loads(sbom_path.read_text(encoding="utf-8"))
    return manifest


def _github_json(url: str, token: str) -> dict[str, Any]:
    req = urllib.request.Request(url, headers={
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
    })
    with urllib.request.urlopen(req, timeout=20) as response:
        return json.loads(response.read().decode("utf-8"))


def _wait_for_required_checks(timeout_seconds: int = 1800) -> dict[str, Any]:
    repository = os.getenv("GITHUB_REPOSITORY")
    token = os.getenv("GITHUB_TOKEN")
    sha = _source_commit()
    if not repository or not token:
        raise RuntimeError("GITHUB_REPOSITORY and GITHUB_TOKEN are required for remote check verification")

    deadline = time.time() + timeout_seconds
    last_summary: dict[str, str] = {}
    while time.time() < deadline:
        payload = _github_json(f"https://api.github.com/repos/{repository}/commits/{sha}/check-runs?per_page=100", token)
        observed: dict[str, str] = {}
        for check in payload.get("check_runs") or []:
            name = str(check.get("name") or "")
            if name in REQUIRED_CHECKS:
                observed[name] = str(check.get("conclusion") or check.get("status") or "")
        last_summary = observed
        missing = sorted(REQUIRED_CHECKS - observed.keys())
        pending = sorted(name for name, state in observed.items() if state in {"queued", "in_progress", "requested", ""})
        failed = sorted(name for name, state in observed.items() if state not in {"success", "queued", "in_progress", "requested", ""})
        if not missing and not pending and not failed:
            return {"status": "PASS", "checks": observed, "sourceCommit": sha}
        if failed:
            raise RuntimeError("required remote checks failed: " + ", ".join(f"{name}={observed[name]}" for name in failed))
        time.sleep(15)
    raise RuntimeError("timed out waiting for required remote checks: " + json.dumps(last_summary, sort_keys=True))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--require-remote-checks", action="store_true")
    parser.add_argument("--remote-timeout-seconds", type=int, default=1800)
    args = parser.parse_args()

    security = _validate_security()
    runtime = _validate_runtime()
    operations = _validate_operations()
    sbom = _validate_sbom()
    remote_checks = _wait_for_required_checks(args.remote_timeout_seconds) if args.require_remote_checks else {"status": "SKIPPED"}

    high_exceptions = int(security["container"].get("exceptionedHighCount") or 0)
    production_release_allowed = high_exceptions == 0
    result = {
        "schemaVersion": "public-preview-release-gate-v1",
        "releaseType": "public-preview",
        "sourceCommit": _source_commit(),
        "workflowRunId": os.getenv("GITHUB_RUN_ID", "local"),
        "generatedAt": datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
        "previewReleaseAllowed": True,
        "productionReleaseAllowed": production_release_allowed,
        "criticalFindings": security["container"].get("criticalFindingCount"),
        "criticalExceptions": security["container"].get("exceptionedCriticalCount"),
        "highFindings": security["container"].get("highFindingCount"),
        "highExceptions": high_exceptions,
        "securityExceptionsPresent": high_exceptions > 0,
        "productionReady": False,
        "checks": {
            "security": "PASS",
            "criticalZero": "PASS",
            "runtime": "PASS",
            "businessE2E": "PASS",
            "operations": "PASS",
            "sbom": "PASS",
            "remoteChecks": remote_checks["status"],
        },
        "evidence": {
            "securityWorkflowRunId": security["container"].get("workflowRunId"),
            "criticalZeroWorkflowRunId": security["criticalZero"].get("workflowRunId"),
            "runtimeWorkflowRunId": runtime["gate"].get("workflowRunId"),
            "operationsWorkflowRunId": operations.get("workflowRunId"),
            "sbomWorkflowRunId": sbom.get("workflowRunId"),
        },
        "boundaries": [
            "PUBLIC_PREVIEW_RELEASE_ALLOWED",
            "PUBLIC_CRITICAL_VULNERABILITIES_ZERO",
            "PUBLIC_CRITICAL_EXCEPTIONS_ZERO",
            "PUBLIC_RUNTIME_VERIFIED",
            "PUBLIC_BUSINESS_E2E_VERIFIED",
            "PUBLIC_OPERATIONS_BASELINE_VERIFIED",
            "PUBLIC_SECURITY_EXCEPTIONS_PRESENT" if high_exceptions else "PUBLIC_SECURITY_EXCEPTIONS_ZERO",
            "PUBLIC_PRODUCTION_RELEASE_BLOCKED" if high_exceptions else "PUBLIC_PRODUCTION_RELEASE_ALLOWED",
            "PRODUCTION_READY_NOT_CLAIMED",
        ],
    }
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "preview-release-gate-result.json").write_text(json.dumps(result, indent=2), encoding="utf-8")

    print("PUBLIC_PREVIEW_RELEASE_ALLOWED")
    print("PUBLIC_CRITICAL_VULNERABILITIES_ZERO")
    print("PUBLIC_CRITICAL_EXCEPTIONS_ZERO")
    print("PUBLIC_RUNTIME_VERIFIED")
    print("PUBLIC_BUSINESS_E2E_VERIFIED")
    print("PUBLIC_OPERATIONS_BASELINE_VERIFIED")
    if high_exceptions:
        print("PUBLIC_SECURITY_EXCEPTIONS_PRESENT")
        print("PUBLIC_PRODUCTION_RELEASE_BLOCKED")
    print("PRODUCTION_READY_NOT_CLAIMED")


if __name__ == "__main__":
    main()
