CREATE TABLE IF NOT EXISTS `litemall_ai_review_risk_task` (
  `id` int NOT NULL AUTO_INCREMENT,
  `analysis_id` int DEFAULT NULL COMMENT 'AI分析ID',
  `source_type` varchar(32) DEFAULT NULL COMMENT '来源类型',
  `source_id` int DEFAULT NULL COMMENT '来源ID',
  `review_id` varchar(64) DEFAULT NULL COMMENT '评论ID',
  `product_id` int DEFAULT NULL COMMENT '商品ID',
  `product_name` varchar(127) DEFAULT NULL COMMENT '商品名称',
  `review_text` text COMMENT '评论文本',
  `image_url` varchar(512) DEFAULT NULL COMMENT '图片URL',
  `risk_type` varchar(64) NOT NULL COMMENT '风险类型',
  `risk_level` varchar(32) NOT NULL COMMENT '风险等级',
  `sentiment_label` varchar(32) DEFAULT NULL COMMENT '情感标签',
  `confidence` decimal(6,4) DEFAULT NULL COMMENT '置信度',
  `conflict_score` decimal(6,4) DEFAULT NULL COMMENT '冲突分',
  `status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '处理状态',
  `handler` varchar(64) DEFAULT NULL COMMENT '处理人',
  `handle_note` varchar(512) DEFAULT NULL COMMENT '处理备注',
  `created_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_analysis_risk_type` (`analysis_id`, `risk_type`),
  KEY `idx_status` (`status`),
  KEY `idx_risk_level` (`risk_level`),
  KEY `idx_risk_type` (`risk_type`),
  KEY `idx_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI评论风险任务表';
