CREATE TABLE IF NOT EXISTS `litemall_review_ai_analysis` (
  `id` int NOT NULL AUTO_INCREMENT,
  `source_type` varchar(32) DEFAULT NULL COMMENT 'analysis source type',
  `source_id` int DEFAULT NULL COMMENT 'analysis source id',
  `review_id` varchar(64) NOT NULL COMMENT '评论ID或手工分析ID',
  `product_id` int NOT NULL COMMENT '商品ID',
  `product_name` varchar(127) NOT NULL COMMENT '商品名称',
  `review_text` text NOT NULL COMMENT '评论文本',
  `rating` tinyint DEFAULT NULL COMMENT '用户评分',
  `image_urls` text COMMENT '评论图片URL JSON',
  `sentiment_label` varchar(32) NOT NULL COMMENT '情感标签',
  `confidence` decimal(6,4) DEFAULT NULL COMMENT '置信度',
  `positive_score` decimal(6,4) DEFAULT NULL COMMENT '正向分',
  `neutral_score` decimal(6,4) DEFAULT NULL COMMENT '中性分',
  `negative_score` decimal(6,4) DEFAULT NULL COMMENT '负向分',
  `evidence_json` text COMMENT '证据 JSON',
  `similar_cases_json` mediumtext COMMENT '相似案例 JSON',
  `agent_suggestion_json` text COMMENT '智能体建议 JSON',
  `workflow_trace_json` mediumtext COMMENT '智能体流程 JSON',
  `add_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_review_ai_product_id` (`product_id`),
  KEY `idx_review_ai_source` (`source_type`, `source_id`),
  KEY `idx_review_ai_sentiment_label` (`sentiment_label`),
  KEY `idx_review_ai_add_time` (`add_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='评论AI分析结果表';
