CREATE TABLE IF NOT EXISTS `litemall_ai_agent_run` (
  `id` int NOT NULL AUTO_INCREMENT,
  `run_no` varchar(64) NOT NULL,
  `trigger_type` varchar(32) DEFAULT NULL,
  `source_type` varchar(32) DEFAULT NULL,
  `source_id` int DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'running',
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `duration_ms` bigint DEFAULT NULL,
  `input_summary` varchar(1024) DEFAULT NULL,
  `final_result` varchar(1024) DEFAULT NULL,
  `error_message` varchar(1024) DEFAULT NULL,
  `state_snapshot_json` mediumtext,
  `llm_provider` varchar(64) DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `prompt_template` varchar(128) DEFAULT NULL,
  `schema_valid` tinyint(1) DEFAULT NULL,
  `schema_error` varchar(1024) DEFAULT NULL,
  `repair_used` tinyint(1) DEFAULT 0,
  `fallback_used` tinyint(1) DEFAULT 0,
  `token_usage_input` int DEFAULT NULL,
  `token_usage_output` int DEFAULT NULL,
  `latency_ms` bigint DEFAULT NULL,
  `rag_enabled` tinyint(1) DEFAULT 0,
  `rag_strategy` varchar(32) DEFAULT NULL,
  `retrieval_hit_count` int DEFAULT 0,
  `retrieval_top_score` decimal(10,6) DEFAULT NULL,
  `embedding_provider` varchar(64) DEFAULT NULL,
  `reranker_provider` varchar(64) DEFAULT NULL,
  `retrieval_latency_ms` bigint DEFAULT NULL,
  `route_decision` varchar(64) DEFAULT NULL,
  `route_reason` varchar(512) DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_run_no` (`run_no`),
  KEY `idx_agent_run_source` (`source_type`, `source_id`),
  KEY `idx_agent_run_status` (`status`),
  KEY `idx_agent_run_created` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `litemall_ai_agent_step` (
  `id` int NOT NULL AUTO_INCREMENT,
  `run_id` int NOT NULL,
  `step_name` varchar(64) NOT NULL,
  `step_order` int DEFAULT NULL,
  `agent_role` varchar(64) DEFAULT NULL,
  `agent_goal` varchar(255) DEFAULT NULL,
  `tool_name` varchar(64) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'success',
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `duration_ms` bigint DEFAULT NULL,
  `input_json` mediumtext,
  `output_json` mediumtext,
  `error_message` varchar(1024) DEFAULT NULL,
  `llm_provider` varchar(64) DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `prompt_template` varchar(128) DEFAULT NULL,
  `schema_valid` tinyint(1) DEFAULT NULL,
  `schema_error` varchar(1024) DEFAULT NULL,
  `repair_used` tinyint(1) DEFAULT 0,
  `fallback_used` tinyint(1) DEFAULT 0,
  `token_usage_input` int DEFAULT NULL,
  `token_usage_output` int DEFAULT NULL,
  `latency_ms` bigint DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_agent_step_run` (`run_id`),
  KEY `idx_agent_step_tool` (`tool_name`),
  KEY `idx_agent_step_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `litemall_ai_agent_feedback` (
  `id` int NOT NULL AUTO_INCREMENT,
  `risk_task_id` int DEFAULT NULL,
  `analysis_id` int DEFAULT NULL,
  `source_type` varchar(32) DEFAULT NULL,
  `source_id` int DEFAULT NULL,
  `feedback_type` varchar(64) NOT NULL,
  `feedback_label` varchar(127) DEFAULT NULL,
  `feedback_note` varchar(1024) DEFAULT NULL,
  `operator` varchar(64) DEFAULT NULL,
  `created_time` datetime DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_agent_feedback_task` (`risk_task_id`),
  KEY `idx_agent_feedback_analysis` (`analysis_id`),
  KEY `idx_agent_feedback_source` (`source_type`, `source_id`),
  KEY `idx_agent_feedback_type` (`feedback_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
