CREATE TABLE IF NOT EXISTS `litemall_ai_governance_observation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `event_type` varchar(32) NOT NULL COMMENT 'decision|human_review|qa_audit|shadow_audit',
  `analysis_id` int DEFAULT NULL,
  `risk_task_id` int DEFAULT NULL,
  `review_id` varchar(64) DEFAULT NULL,
  `route` varchar(32) DEFAULT NULL,
  `decision` varchar(32) DEFAULT NULL,
  `evidence_status` varchar(32) DEFAULT NULL,
  `retrieval_mode` varchar(64) DEFAULT NULL,
  `risk_types_json` varchar(1024) DEFAULT NULL,
  `workflow_version` varchar(64) DEFAULT NULL,
  `governance_schema_version` varchar(64) DEFAULT NULL,
  `policy_index_version` varchar(128) DEFAULT NULL,
  `embedding_model` varchar(128) DEFAULT NULL,
  `latency_ms` bigint DEFAULT NULL,
  `human_decision` varchar(32) DEFAULT NULL,
  `human_reason_code` varchar(64) DEFAULT NULL,
  `audit_result` varchar(32) DEFAULT NULL,
  `shadow_decision` varchar(32) DEFAULT NULL,
  `shadow_disagreement` tinyint(1) DEFAULT 0,
  `evidence_refs` varchar(1024) DEFAULT NULL COMMENT 'bounded citation id/source/hash refs only',
  `created_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_governance_observation_created` (`created_time`),
  KEY `idx_governance_observation_event` (`event_type`, `created_time`),
  KEY `idx_governance_observation_review` (`review_id`),
  KEY `idx_governance_observation_task` (`risk_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='E-Review governance quality observations; no review body or policy body';
