$ErrorActionPreference = "Stop"

$Root = "D:\EReviewAgent\litemall-v24-goldenpath"
$Python = "D:\anaconda\envs\ereview-v24-transformers451\python.exe"

$env:AGENT_RAG_V22_ASSET_MANIFEST = "D:\EReviewAgent\models\v2.2\manifests\v22-real-model-assets.json"
$env:RAG_DENSE_PROVIDER = "bge-m3"
$env:RAG_DENSE_FALLBACK_PROVIDER = "disabled"
$env:RAG_DEFAULT_RETRIEVAL_MODE = "hybrid-real"
$env:RAG_INDEX_ROOT = "D:\EReviewAgent\litemall-v24-goldenpath\docs\v24_golden_path_live\runtime-evidence\model\live-faiss-index"
$env:RAG_BGE_M3_MODEL_PATH = "D:\EReviewAgent\models\bge-m3"
$env:RAG_BGE_M3_PROVIDER_IMPL = "flagembedding"
$env:RAG_BGE_M3_DEVICE = "cuda"
$env:RAG_BGE_M3_USE_FP16 = "true"
$env:RAG_BGE_M3_BATCH_SIZE = "2"
$env:RAG_BGE_M3_MAX_LENGTH = "384"
$env:RAG_REAL_DENSE_REQUIRED = "true"

$env:RAG_RERANKER_TYPE = "local-model"
$env:RAG_RERANKER_PROVIDER_IMPL = "flagembedding"
$env:RAG_RERANKER_MODEL_PATH = "D:\EReviewAgent\models\v2.2\bge-reranker-v2-m3"
$env:RAG_RERANKER_DEVICE = "cuda"
$env:RAG_RERANKER_USE_FP16 = "true"
$env:RAG_RERANKER_BATCH_SIZE = "2"
$env:RAG_RERANKER_MAX_LENGTH = "384"
$env:RAG_RERANKER_CANDIDATE_K = "12"
$env:RAG_RERANKER_FINAL_K = "3"
$env:RAG_RERANKER_TIMEOUT_MS = "90000"
$env:RAG_RERANKER_QUEUE_TIMEOUT_MS = "30000"
$env:RAG_REAL_RERANKER_REQUIRED = "true"

$env:AGENT_LLM_MODEL_PATH = "D:\EReviewAgent\models\v2.2\qwen3-1.7b"
$env:AGENT_LLM_PROVIDER = "local_qwen3_transformers"
$env:AGENT_RAG_LLM_PROVIDER = "local_qwen3_transformers"
$env:AGENT_LLM_DEVICE = "cuda"
$env:AGENT_LLM_DTYPE = "bfloat16"
$env:AGENT_LLM_MAX_INPUT_TOKENS = "2048"
$env:AGENT_LLM_MAX_OUTPUT_TOKENS = "256"
$env:AGENT_LLM_TIMEOUT_MS = "180000"
$env:AGENT_RAG_LOCAL_LLM_ENABLED = "true"
$env:AGENT_REAL_LLM_REQUIRED = "true"
$env:RAG_RULE_FALLBACK_ENABLED = "false"
$env:AGENT_RAG_TARGET_MODE = "governed-local"

Set-Location "$Root\ai-service"
& $Python -m uvicorn app.main:app --host 127.0.0.1 --port 8008 --log-level info
